version: '2'

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - vhost_no_ssl:/etc/nginx/vhost_no_ssl.d # Mounted to keep it in use for backups
      - /usr/share/nginx/html
      - ssl_certs:/etc/nginx/certs:ro
      - staticfiles_data:/srv/api/breazehome.com/static
      - image_data:/srv/api/breazehome.com/images

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - vhost:/etc/nginx/vhost.d
    volumes_from:
      - nginx
    depends_on:
      - letsencrypt-nginx-proxy-companion
      - nginx
      - desktop
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ssl_certs:/etc/nginx/certs:rw
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
  
  git:
    restart: always
    image: gogs/gogs
    container_name: git
    environment:
      - VIRTUAL_HOST=git.breazehome.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=git.breazehome.com
    env_file: .env
    ports:
      - "2222:22"
      - "3000:3000"
    volumes:
      - gogs_data:/data

  desktop:
    restart: always
    build: ./breaze-desktop
    container_name: desktop
    environment:
      - VIRTUAL_HOST=breazehome.com,www.breazehome.com
      - LETSENCRYPT_HOST=breazehome.com,www.breazehome.com
    env_file: .env
    ports:
      - "9000:9000"
    links:
      - api
      - chat:chat_server
  
  api:
    restart: always
    build: ./breaze-api
    container_name: api
    environment:
      - VIRTUAL_HOST=api.breazehome.com
      - LETSENCRYPT_HOST=api.breazehome.com
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - image_data:/srv/images
      - staticfiles_data:/static
      - ./backup/:/usr/src/app/backup/
      - chat_images:/srv/chat_images
    links:
      - db
      - redis
      - memcached
    command: ["./wait-for-it.sh", "db:5432", "--", "/bin/bash", "docker-entrypoint.sh"]

  db:
    restart: always
    image: mdillon/postgis
    container_name: db
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    restart: always
    build: redis
    volumes:
      - redis_data:/data

  memcached:
    restart: always
    image: memcached

  wiki:
    restart: always
    build: ./breaze-wiki
    image: mazzolino/tiddlywiki
    container_name: wiki
    environment:
      - VIRTUAL_HOST=wiki.breazehome.com
      - LETSENCRYPT_HOST=wiki.breazehome.com
    env_file: .env
    ports:
      - "8890:8080"
    volumes:
      - wiki_data:/var/lib/tiddlywiki
    command:  ["/bin/bash", "/usr/local/bin/init-and-run-wiki"]

  doc:
    restart: always
    build: ./breaze-desktop-doc
    container_name: doc
    environment:
      - VIRTUAL_HOST=doc.breazehome.com
      - LETSENCRYPT_HOST=doc.breazehome.com
    env_file: .env
    ports:
      - "9999:8000"
    volumes:
      - doc_data:/var/lib/docs

  mobile:
    restart: always
    build: ./breaze-mobile
    container_name: mobile
    environment:
      - VIRTUAL_HOST=m.breazehome.com
      - LETSENCRYPT_HOST=m.breazehome.com
      - VIRTUAL_PORT=8100
    env_file: .env
    ports:
      - "8100:8100"
    volumes:
      - mobile_data:/usr/src/app

  db-dev:
    restart: always
    image: mdillon/postgis
    container_name: db-dev
    env_file: .env.dbdev
    ports:
      - "5434:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  chat:
    restart: always
    build: ./breaze-chat
    container_name: chat
    environment:
      - VIRTUAL_HOST=chat.breazehome.com
      - LETSENCRYPT_HOST=chat.breazehome.com
      - ALLOWED_ORIGINS=//breazehome.com,//www.breazehome.com
    env_file: .env
    ports:
      - "4000:4000"
    volumes:
      - chat_images:/usr/src/app/uploads
    links:
      - db

  wikidb:
    restart: always
    image: mongo
    container_name: wikidb
    expose:
      - '27017'
    command: '--smallfiles --logpath=/dev/null'
    volumes:
      - wikijs_mongo:/data/db

  wikijs:
    restart: always
    image: 'requarks/wiki:latest'
    container_name: wikijs
    environment:
      - VIRTUAL_HOST=wikijs.breazehome.com
      - LETSENCRYPT_HOST=wikijs.breazehome.com
      - WIKIJS_HOST=https://wikijs.breazehome.com
    env_file: .env
    ports:
      - "3333:3000"
    volumes:
      - ./breaze-wikijs/config/config.yml:/var/wiki/config.yml
      - wikijs_data:/usr/src/app/
    links:
      - wikidb
      - git

volumes:
  image_data:
    driver: local

  postgres_data:
    driver: local

  gogs_data:
    driver: local

  redis_data:
    driver: local

  staticfiles_data:
    driver: local
  
  wiki_data:
    driver: local

  doc_data:
    driver: local

  ssl_certs:
    driver: local

  mobile_data:
    driver: local

  postgres_dev_data:
    driver: local

  vhost:
    driver: local

  vhost_no_ssl:
    driver: local

  chat_images:
    driver: local

  wikijs_data:
    driver: local

  wikijs_mongo:
    driver: local